### ISSUE TITLE
grafana-import-dashboards Completed 

### ISSUE THREAD

**Issue by liuhaibo0303** [giantswarm/prometheus#124]
[k8s@kube-node1 ~]$ kubectl get pod -n monitoring 
NAME                                  READY     STATUS      RESTARTS   AGE
alertmanager-6bc6f8b766-dq6k4         1/1       Running     0          15m
grafana-core-768776f5c9-d495q         1/1       Running     0          33m
grafana-import-dashboards-czpf4       0/1       Completed   0          33m
kube-state-metrics-84bd4b69b7-klbld   1/1       Running     0          9m
node-directory-size-metrics-4k248     2/2       Running     0          33m
node-directory-size-metrics-b4hmm     2/2       Running     0          33m
node-directory-size-metrics-qk6pt     2/2       Running     0          33m
prometheus-core-fd6c87c77-sxxxb       1/1       Running     0          33m
prometheus-node-exporter-l2xxz        1/1       Running     0          33m
prometheus-node-exporter-r7sg4        1/1       Running     0          33m
prometheus-node-exporter-wwkq6        1/1       Running     0          33m
[k8s@kube-node1 ~]$

[k8s@kube-node1 ~]$ kubectl -n monitoring logs grafana-import-dashboards-czpf4 -f
importing prometheus-datasource.json
{"id":1,"message":"Datasource added","name":"prometheus"}
importing grafana-net-2-dashboard.json
{"pluginId":"","title":"Prometheus Stats","imported":true,"importedUri":"db/prometheus-stats","slug":"","importedRevision":1,"revision":1,"description":"","path":"","removed":false}
importing grafana-net-737-dashboard.json
{"pluginId":"","title":"Kubernetes Pod Resources","imported":true,"importedUri":"db/kubernetes-pod-resources","slug":"","importedRevision":1,"revision":1,"description":"","path":"","removed":false}

why the status of pod who names "grafana-import-dashboards" is Completed , help!

**Comment by ak2766** [comment]
That's an init container.  It is normally used to ensure that a certain action occurs before some other action can take place.  They run to completion and are only run once.  See [Understanding Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) for further explanation.

**Comment by pipo02mix** [comment]
yeah @ak2766 is right, thx
