### ISSUE TITLE
Issue w/ Quick start instructions

### ISSUE THREAD

**Issue by peter-chen-icann** [giantswarm/prometheus#130]
When running the quick start instructions:

kubectl apply -f https://raw.githubusercontent.com/giantswarm/kubernetes-prometheus/master/manifests-all.yaml

I'm getting this error:

error: unable to read URL "https://raw.githubusercontent.com/giantswarm/kubernetes-prometheus/master/manifests-all.yaml", server reported 404 Not Found, status code=404

**Comment by pipo02mix** [comment]
URL has changed because we renamed the project, please try

`kubectl apply -f https://raw.githubusercontent.com/giantswarm/prometheus/master/manifests-all.yaml`
