### ISSUE TITLE
node-directory-size-metrics - high memory utilization

### ISSUE THREAD

**Issue by NicklasWallgren** [giantswarm/prometheus#132]
The node-directory-size-metrics pods are utilizing a large amount of memory, as high as 3680Mi. 

kubectl top pods -n=monitoring
```
NAME                                  CPU(cores)   MEMORY(bytes)   
alertmanager-5ddcdf6fdd-h646t         1m           11Mi            
grafana-core-6dfd47c968-fp58p         1m           15Mi            
kube-state-metrics-6c4bb8d569-4smwt   8m           10Mi            
node-directory-size-metrics-5qhb4     1m           7Mi             
node-directory-size-metrics-qkgtc     1m           3680Mi          
prometheus-core-87df4b8c8-7schh       62m          177Mi           
prometheus-node-exporter-fq8xs        2m           10Mi            
prometheus-node-exporter-tqr8v        2m           9Mi   
```

**Comment by pipo02mix** [comment]
We are not actively maintaining the manifest yaml anymore, but we are glad to receive contributions. We will encourage you to run Prometheus through the [Prometheus Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator). This implementation uses node exporter to get node metrics and you can create alerts or dashboards based on that.
